from animation import UNIT

MAX_IDLE_CHARACTERS_NUM = 10
MAX_ITEMS_NUM = 5
MAX_WEAPONS_NUM = 10

SCREEN_WIDTH = 1440
SCREEN_HEIGHT = 896

MAP_WIDTH = SCREEN_WIDTH // UNIT
MAP_HEIGHT = SCREEN_HEIGHT // UNIT